#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Stop at first error
set -e

# Check if OpenFOAM/FOAM has been sourced
if [[ -z "${WM_PROJECT}" ]]
then
    echo "Please source the OpenFOAM/FOAM bashrc first!"
    exit 1
fi

# Check required environment variables are set
if [[ -z "${SOLIDS4FOAM_INST_DIR}" ]]
then
    echo "Please set the SOLIDS4FOAM_INST_DIR environment variable!"
    exit 1
fi
if [[ -z "${PYBIND11_INC_DIR}" ]]
then
    echo "Please set the PYBIND11_INC_DIR environment variable!"
    exit 1
fi
if [[ -z "${PYBIND11_LIB_DIR}" ]]
then
    echo "Please set the PYBIND11_LIB_DIR environment variable!"
    exit 1
fi

# Run the cases

echo "Running the calculation"
(cd 3x3LinReg && python selfsim_linear_elastic.py && python post_processor.py) &
(cd 3x3NN && python selfsim_linear_elastic.py && python post_processor.py) &
(cd 6x6LinReg && python selfsim_linear_elastic.py && python post_processor.py) &
(cd 6x6NN && python selfsim_linear_elastic.py && python post_processor.py) &

# Wait for all background processes to finish
wait

echo "Calculation complete."

mkdir -p SelfSim

cp -r 6x6NN/NNBased/pythonNNBasePlateHole/Results/*loadInc1 SelfSim/
cp -r 6x6NN/NNBased/pythonNNBasePlateHole/Results/*loadInc5 SelfSim/
cp -r 6x6NN/NNBased/pythonNNBasePlateHole/Results/*loadInc15 SelfSim/

python plot_error.py